### ISSUE TITLE
Review OxO API to define initial set of services

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-api#2]
Review the OxO API and create a list of services we need to implement. (Just a bullet point list in this ticket)

**Comment by matentzn** [comment]
https://www.ebi.ac.uk/spot/oxo/docs/api

**Comment by anitacaron** [comment]
- /datasources
- /datasources/{datasource-id}
- /mappings
- /mappings/{mapping-id}
- /terms
- /terms/{term-id}
- /search

**Comment by anitacaron** [comment]
After meetings, it was decided that we'll build the OxO 2, which will use only the SSSOM API that not follows the previous API.
